### ISSUE TITLE
Better formatting in fzf

### ISSUE THREAD

**Issue by IngoMeyer441** [thirteen37/fzf-alias#2]
This is a modified version of your `fzf_alias` function which uses the `column` command to align alias names and alias values:

```shell
function fzf_alias () {
    local selected_alias

    # Modified version of <https://github.com/thirteen37/fzf-alias/blob/main/fzf-alias.plugin.zsh>
    selected_alias="$(alias | column -s '=' -t -l 2 | fzf --query "${BUFFER}" | awk '{ print $1 }')"
    if [[ -n "${selected_alias}" ]] ; then
        BUFFER="${selected_alias}"
    fi
    zle redisplay
}
```

Perhaps this is also interesting for you.

**Comment by thirteen37** [comment]
Thanks for the suggestion. It's a good idea.

Unfortunately, `column` on MacOS/BSD doesn't support the `-l` option. Let me find another solution.

**Comment by thirteen37** [comment]
Ugly hack by adding `sed` into the chain.
